### ISSUE TITLE
Hey I need some help here.

### ISSUE THREAD

**Issue by GhostieSpook** [Zandew/MiniMusicWidget#1]
So. It looks really cool, but I'm not the brightest and don't quite know how to actually get it onto my Mac.

**Comment by Zandew** [comment]
Hello, thank you for your interest in this project! I have pushed a new folder `Builds` and inside contains `Oracle.app`. You can either clone this repository and use that file or open in Xcode and build it yourself. This app currently is not ready for production, and please leave any feedback you may have.
