### ISSUE TITLE
Application Freezes when trying to log in.

### ISSUE THREAD

**Issue by GhostieSpook** [Zandew/MiniMusicWidget#2]
So I got it working, but it stopped after a day and ended up logging me out? And won't log back in, but instead leaves me at this screen. Anything I can do to fix it?
https://i.umai.pw/cTpF02.png

**Comment by Zandew** [comment]
Hello, when you start the app, is it still prompting you to log in, or does it directly send you to this blank window? Also, when you close and click the menu bar icon, does it still send you this screen?

**Comment by GhostieSpook** [comment]
Just sends me the blank window. Both when I start the app and click the icon in the menu bar.

**Comment by GhostieSpook** [comment]
Any updates?

**Comment by Zandew** [comment]
Sorry about this, I'm still struggling to recreate this on my end. For the meantime, could you try reinstalling the app and seeing if the same thing happens?
